//
//  AppUser.swift
//  LoginApp
//
//  Created by Jatin Gupta on 2025-09-12.
//


import Foundation
import CryptoKit
import FirebaseFirestore

/// Defines the different user roles in the courier application
/// Each role has specific permissions and access to different features
enum UserRole: String, Codable, CaseIterable {
    /// Regular customer who can create and track orders
    case user = "user"
    
    /// Driver who can accept and fulfill delivery orders
    case driver = "driver"
    
    /// Administrator with full system access and management capabilities
    case admin = "admin"
    
    /// Human-readable display name for the role
    /// Used in UI to show role to users
    var displayName: String {
        switch self {
        case .user: return "Customer"
        case .driver: return "Driver"
        case .admin: return "Admin"
        }
    }
}

/// Represents a user account in the courier system
/// Contains all user information, authentication data, and role-based permissions
/// Note: This is separate from the `User` type used for users.json to avoid naming conflicts
struct AppUser: Codable, Identifiable {
    /// Unique identifier for the user (auto-generated by Firebase)
    @DocumentID var id: String?
    
    /// User's full name as displayed in the app
    var fullName: String
    
    /// User's email address (used for authentication)
    var email: String
    
    /// User's phone number for contact purposes
    var phone: String
    
    /// Hashed password (empty for Firebase Auth users)
    var passwordHash: String
    
    /// Unique token for user identification (usually same as Firebase UID)
    var token: String
    
    /// User's role determining their permissions and access level
    var role: UserRole = .user
    
    /// Whether the user account is active and can log in
    var isActive: Bool = true
    
    /// Timestamp when the user account was created
    var createdAt: Date = Date()
    
    /// Timestamp when the user account was last updated
    var updatedAt: Date = Date()

    /// Creates a new user account with the specified parameters
    /// - Parameters:
    ///   - id: Optional unique identifier (auto-generated if nil)
    ///   - fullName: User's full name
    ///   - email: User's email address
    ///   - phone: User's phone number
    ///   - passwordHash: Hashed password (empty for Firebase Auth)
    ///   - token: Unique token for identification (auto-generated if not provided)
    ///   - role: User's role in the system (defaults to .user)
    init(
        id: String? = nil,
        fullName: String,
        email: String,
        phone: String,
        passwordHash: String = "",
        token: String = UUID().uuidString,
        role: UserRole = .user
    ) {
        self.id = id
        self.fullName = fullName
        self.email = email
        self.phone = phone
        self.passwordHash = passwordHash
        self.token = token
        self.role = role
        self.createdAt = Date()
        self.updatedAt = Date()
    }
}

final class AuthStore: ObservableObject {
    @Published var currentUser: AppUser? = nil

    private let key = "registered_users_v1"

    // MARK: - Public API

    func register(fullName: String, email: String, phone: String, password: String) throws {
        var users = loadRegistered()
        guard users.first(where: { $0.email.caseInsensitiveCompare(email) == .orderedSame }) == nil else {
            throw NSError(domain: "Auth", code: 1, userInfo: [NSLocalizedDescriptionKey: "An account with this email already exists."])
        }
        let hash = Self.hash(password: password)
        let user = AppUser(fullName: fullName, email: email, phone: phone, passwordHash: hash)
        users.append(user)
        saveRegistered(users)
        currentUser = user
    }

    /// Returns the authenticated user if valid, otherwise nil
    func signIn(email: String, password: String, bundledFallback: [AppUser] = []) -> AppUser? {
        let hash = Self.hash(password: password)

        // 1) Check registered users
        var users = loadRegistered()
        if let u = users.first(where: { $0.email.caseInsensitiveCompare(email) == .orderedSame && $0.passwordHash == hash }) {
            currentUser = u
            return u
        }

        // 2) Fallback: bundled users (converted to AppUser)
        if let u = bundledFallback.first(where: { $0.email.caseInsensitiveCompare(email) == .orderedSame && $0.passwordHash == hash }) {
            // Optional: persist this bundled user into registered list so it behaves like a normal account
            users.append(u)
            saveRegistered(users)
            currentUser = u
            return u
        }

        return nil
    }

    // MARK: - Registered storage

    func loadRegistered() -> [AppUser] {
        guard let data = UserDefaults.standard.data(forKey: key),
              let list = try? JSONDecoder().decode([AppUser].self, from: data) else {
            return []
        }
        return list
    }

    private func saveRegistered(_ users: [AppUser]) {
        if let data = try? JSONEncoder().encode(users) {
            UserDefaults.standard.set(data, forKey: key)
        }
    }

    // MARK: - Utilities

    static func hash(password: String) -> String {
        let digest = SHA256.hash(data: Data(password.utf8))
        return digest.map { String(format: "%02x", $0) }.joined()
    }
}
